// Pins parameters
#define CON1_GPIO GPIO_NUM_26
#define CON2_GPIO GPIO_NUM_27
#define CON3_GPIO GPIO_NUM_25

// Matrix parameters
#define MCON1_GPIO GPIO_NUM_32
#define MATRIX_WIDTH 8
#define MATRIX_LENGTH 8
#define MATRIX_AREA MATRIX_LENGTH * MATRIX_WIDTH